### ISSUE TITLE
gamepad_get_device_count not working correctly

### ISSUE THREAD

**Issue by SuperRiderTH** [enigma-dev/enigma-dev#1000] opened 2016-08-15 00:14 UTC
gamepad_get_device_count returns 32437344 with no controllers plugged in, and returns 32437345 with one plugged in.

This is quite wrong, and can cause game hanging with code such as:
`for (i=0; i<gamepad_get_device_count(); i+=1)`

**Comment by RobertBColton** [comment] 2016-08-15 11:47
This is corrected in #966 and the function will work the same as Studio after I finish that PR. In other words, it will always report 4 on Windows and then you have to use gamepad_is_connected to see the actual number of connected devices.

https://docs.yoyogames.com/source/dadiospice/002_reference/mouse,%20keyboard%20and%20other%20controls/gamepad%20input/gamepad_get_device_count.html

It will now just return the XInput constant XUSER_MAX_COUNT. Never hard code 4 into a game btw as it is possible, though highly unlikely, that Microsoft could update XInput with more controllers in the future.

**Comment by RobertBColton** [comment] 2018-12-11 00:39
Ok, since #966 went stale, I had to include this fix in #1452 that I will have Josh review tonight. The issue was caused by the fact I never initialized the local int I used for counting the devices. Regardless, I've changed the function to return the XUSER_MAX_COUNT, which is 4, so it's the same as GMS for now.

**Comment by RobertBColton** [comment] 2018-12-11 04:34
Closing as resolved by #1452.

**Closed** 2018-12-11 04:33 UTC
Labels: Bug, Reproducible, Xinput
