### ISSUE TITLE
Instance Deactivation Errors

### ISSUE THREAD

**Issue by polygoned** [enigma-dev/enigma-dev#427] opened 2013-10-12 00:31 UTC
Lumping these together as there are a few. josh has said that he's going to redo the system properly.

- [x] reactivating deactivated instances results in a crash #85
- [x] `instance_activate_object` does not work on children after parent is deactivated #252
- [x] deactivated instances are not cleared on `game_restart` #237

**Comment by RobertBColton** [comment] 2018-05-13 14:41
@JoshDreamland I am closing this because none of them are reproducible on master anymore. I tried to reproduce them and have provided test GMK projects on each of the three issues which should reproduce the issues, but they don't. I further tracked down the issues/commits where I believe they were fixed and it's mostly thanks to sorlok's work.

Even though you haven't gotten around to your threaded instance activation design yet, this issue is basically resolved.

**Closed by RobertBColton** 2018-05-13 14:41 UTC
Labels: Bug, Instances
