### ISSUE TITLE
Compiling anything without admin approval leads to bizzare errors?

### ISSUE THREAD

**Issue by BPzeBanshee** [enigma-dev/enigma-dev#994] opened 2016-08-11 08:30 UTC
output_log.txt = http://pastebin.com/xm1uYtEH
Progress window = http://pastebin.com/g0TsWrQS
Updated ENIGMA today by running the git-bash.bat and then typing "update", when I run a blank room I get a "Failed to compile at C++ Level".

**Comment by JoshDreamland** [comment] 2016-08-11 12:20
Could you pastebin the lines of `C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_roomarrays.h` above line 164? Or just the whole file?

**Comment by faissaloo** [comment] 2016-08-11 12:25
What version of GCC do you have? Have you tried reinstalling ENIGMA?

**Comment by BPzeBanshee** [comment] 2016-08-12 02:56
http://pastebin.com/tJXRxuRU

This is odd. I first tested with Warbird but when closing and starting the program I ran a blank room yet this IDE_EDIT_roomarrays.h still refers to the Warbird rooms.

git-bash.bat reports GCC 4.8.2, which would I assume be whatever the ENGIMA portable build came with at the time. I downloaded and reinstalled several times on the last problem I had which didn't help so I'm a bit apprehensive about doing the same here.

**Comment by JoshDreamland** [comment] 2016-08-12 03:02
That is bizarre... perhaps the file is really old, and that's why the room creation codes don't have the expected prototype? Try cleaning the build (there's a button for it in LGM if you can't do it manually).

**Comment by BPzeBanshee** [comment] 2016-08-12 03:08
I tried cleaning the build from the button you describe which didn't work, so I manually deleted the C:\ProgramData\ENIGMA folder. From there I was able to compile an empty room but when testing Warbird afterwards I got the return of this error: http://enigma-dev.org/forums/index.php?topic=1396.msg26047#msg26047
which I then solved by re-enabling Run as Administrator in the Compatibility tab for ENIGMA.exe.

Seems to be a permissions problem. Very obtuse way of showing it, and I don't recall it doing this in previous builds.

**Comment by JoshDreamland** [comment] 2016-08-12 03:51
Why does ENIGMA not have access to its own ProgramData folder, on Windows? ...bleh. I'll keep that in mind for next time.

**Comment by RobertBColton** [comment] 2016-08-12 08:09
ENIGMA should be run with administrative privileges, that much I already knew. But I think it's only AppData they can write to without admin privileges Josh. TBH, I really have no idea but I think that's the case since GMS uses %APPDATA%/Roaming.

**Comment by JoshDreamland** [comment] 2016-08-12 12:46
Not if the installer created the folder with administrative privileges. When is that folder created? What so is in it? Perhaps we should just move the compiler output to APPDATA on Windows. Linux stores it in `~/.enigma`.

**Comment by RobertBColton** [comment] 2016-08-12 14:33
https://github.com/enigma-dev/enigma-dev/blob/master/settings.ey#L43

The Default-Windows stuff was my doing, I updated ey a long time ago to make it do that. So anyway it's a per project setting. The reason I did that was because I was thinking of other IDE's like Qt Creator and stuff where you normally specify that in a project file. Really though I don't think ENIGMA needs it at that level? Should we make it a global ENIGMA setting instead?

**Comment by JoshDreamland** [comment] 2016-08-12 16:51
I think it's fine to have it configured in the project. I don't know if people are using it, but it's a neat feature that's out of the way. What's important is a reasonable default. A reasonable default should work without admin rights, though.

**Comment by RobertBColton** [comment] 2016-08-12 17:28
The one downside though Josh is people were confused when they would take an EGM to a different platform and it wouldn't compile because it was trying to use a different platform's make directory. What could be done about that?

**Comment by JoshDreamland** [comment] 2016-08-12 21:09
Perhaps I misunderstand the purpose of the default values; are we copying them into people's project configs when they don't set them? We should probably not be copying defaults at all. While it's possible that breaking changes to defaults could be aggravating, I think the benefits outweigh the costs. I'll think more on that with time.

But we should **definitely** not be copying platform-specific defaults into a platform-agnostic field. This problem is bigger than this bug report, and will really bite us in the long run. What's the point of different default values for different platforms if you can't *manually* configure different values for different platforms? That's the first thing to address. We'll worry about the issue of removing this individual project setting later.

**Comment by RobertBColton** [comment] 2016-08-12 22:00
Right, exactly, that is the problem. I have nothing more to say for now.

**Comment by RobertBColton** [comment] 2016-08-23 15:16
Hey guys, I also found that GMS still uses ProgramData.
http://help.yoyogames.com/hc/en-us/articles/216755378-GameMaker-Studio-Education-Version

> GameMaker still requires a place to write to, so it currently use the windows standard ProgramData (normally found in c:\ProgramData). All users must have read/write access to c:\ProgramData\GameMaker-Studio. Inside here, logs will be stored in a per-user folders. If you ever run into difficulty, then you should delete the contents of this folder, run GameMaker: Studio again, and then zip up the log files and get in touch via the Helpdesk

**Comment by fundies** [comment] 2017-12-24 17:22
@JoshDreamland has confirmed we should be writting to %appdata% not program data

**Comment by RobertBColton** [comment] 2017-12-25 00:53
Resolved by #1121 which discovered that a typical default ENIGMA install should use `%LOCALAPPDATA%` on Windows just like GameMaker: Studio does. This allows each user account to be on a different commit of ENIGMA and also resolves the access rights issues.

**Closed** 2017-12-25 00:53 UTC
Labels: Compiler, Error
