### ISSUE TITLE
Variable/Function/Reserved names Conflicts

### ISSUE THREAD

**Issue by RodrigoCard** [enigma-dev/enigma-dev#1024] opened 2016-09-19 16:04 UTC
If you use a variable/function name that is defined somewhere in the C++ code, the compiler correctly gives the "_invalid assignment to function_" error. Even when they are dot-accessed variables.

Some names that gives errors:
- [connect](http://enigma-dev.org/forums/index.php?topic=2021.msg19971#msg19971)
- time
- select (linux)

---
I Also got parsing errors at C++ level when a script calls variables with C reserved words (but valid GML), such as **char**. You probably can see why :)

---
Would a good solution be prefixing everything before generating the code??

**Comment by RobertBColton** [comment] 2016-09-19 21:04
Yes and this is actually a duplicate of #915, a lot of Win32 functions can conflict too like CreateFont.

I have to close this as a duplicate but for the time being, ENIGMA settings has a keyword blacklist in the Game Settings menu. You can list all the keywords you want mangled on compile.

**Closed by RobertBColton** 2016-09-19 21:04 UTC
