### ISSUE TITLE
Set Correct Context Attributes for Win32/XLib OpenGL3.3

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1765] opened 2019-06-28 19:47 UTC
fundies asked me to report this issue. I'm the one who ran into it, fundies was the one who knew what the problem was - the context attributes are incorrect. He's not wanting to fix it and would prefer Robert would if that's ok with him, or Josh I guess, or whoever else can. I know I can't.

Only the background color is drawn in Win32 and XLib in combination with OpenGL 3.3. OpenGL 3.3 has been tested with SDL as well and I can verify this is not an issue with that platform.

**Comment by RobertBColton** [comment] 2019-06-28 20:03
Closing as duplicate of #1686, Josh does not want to use a fixed 3.3. If you read 1686, I was in disagreement with Josh up to a certain point. Requesting a specific context version makes our GL function like Direct3D does, with static versions. The target either supports it or it doesn't. Josh prefers the dynamic fallback nature of OpenGL. The only problem there is with core contexts, since those must be at least 3.1. However, WGL allows us to work around that by just specifying core attribute, as we do, which gives me a 4.5 core context for ENIGMA's OpenGL3 system. Basically, the version attached to ENIGMA's GL is actually the minimum context that must be supported. SDL's OpenGL wrangling has a bug where the version number must be specified in order to obtain a core context, which is the central issue in #1686. Nothing we can do, it's really just an SDL bug. Feel free to research it further though.

**Closed by RobertBColton** 2019-06-28 20:03 UTC

**Comment by RobertBColton** [comment] 2019-06-28 20:12
The window resizing problems is actually covered by #997 too. I only ever implemented the window resizing and clearing in the Win32 bridges.
https://github.com/enigma-dev/enigma-dev/blob/11c1943c00711bf3e1cf2cbf03933ef0a011c597/ENIGMAsystem/SHELL/Bridges/Win32-Direct3D9/graphics_bridge.cpp#L87

It should be moved either to the general platforms or general graphics. That can only be done when ENIGMA has more comprehensive hooks. Right now we only have `extension_update_hooks` and we would need `extension_window_resize_hooks`. That approach, if continued, is going to get cumbersome, and therefore, we need a more comprehensive solution like #997 that allows us to hook any system or extension into any arbitrary user event (in this case, the Draw Resize event).

**Comment by RobertBColton** [comment] 2019-06-28 21:40
Ok, I'll do it in a few hours, move the window resize stuff. It won't be a fix for the other open issues but will address this specifically.
