### ISSUE TITLE
Collision handling questions.

### ISSUE THREAD

**Issue by KelvinShadewing** [enigma-dev/enigma-dev#1067] opened 2017-07-30 04:13 UTC
I'm asking about these here because even using a brand new email address, it says everything I try to use is already taken, even though password recovery never sends an email.

When I go into the project settings, under ENIGMA>API, there's a box for collision checking, but when I make a sprite, there's also options for collision checking. How does this work? Does one override the other? Does one limit the other?

Also, when I change either option, the bounding box preview for sprites doesn't change between precise and the various shape options; only when I select full image does it change the bounding box.

One last thing, for shape-based collision, does it do actual geometry checking, or just a shaped area for checking pixels? Like, if I check diamond for two sprites, does it use math like point-in-polygone and line-line collision? Or does it just use a region of pixels that fits that shape?

**Comment by JoshDreamland** [comment] 2017-07-30 04:37
I just created a test user without an issue. If you need me to reset a password for you, I can do that.

LateralGM's interface doesn't thoroughly account for ENIGMA's systems capabilities; the UI exposes some features ENIGMA does not offer, and is missing some features ENIGMA offers. We really need a replacement IDE, at this point. Disabling collisions under API settings disables them completely.

I think different bounding box shapes were slapped into Game Maker as an afterthought. I don't know what the state of ENIGMA's support for them is, but LGM's UI does seem to be lacking, there.

I believe ENIGMA's polygon-based collision checking is based on separating axis, but I didn't write any of the collision systems except the basic bounding box one. We don't generate a pixel mask to the shape you're requesting, though, if that's your concern.

**Comment by KelvinShadewing** [comment] 2017-07-30 05:59
There's no password to reset because I can't even make an account. No matter what email I use, even ones I made recently, it always says it's taken.

As for getting anything to build in Enigma, do you have any ideas? I must be doing something wrong, because I don't see anyone else not being able to build a minium app with it.

**Comment by JoshDreamland** [comment] 2017-07-30 13:49
The system doesn't actually make you verify your email, so you can use anything shaped like an email address. If there is a bug in that system, I can't reproduce it... and we're contacting the same server.

I saw your build issue. It's just a linker error; you could fix it by defining that hWnd variable in any source file. I don't know why it's gone missing, or why no one has reported it but you. I'd try to diagnose, but I don't run Windows. The haven't been any recent changes affecting it.

**Comment by KelvinShadewing** [comment] 2017-08-04 01:39
> I saw your build issue. It's just a linker error; you could fix it by defining that hWnd variable in any source file. I don't know why it's gone missing, or why no one has reported it but you. I'd try to diagnose, but I don't run Windows. There haven't been any recent changes affecting that system.

I responded in that thread.

Glad to hear shapes use actual shapes and not pixel masks, cuz I think Game Maker does that. So, disabling it there disables them all, but if you pick precise or shape under the API, how does that effect the individual options on the sprite editor?

**Comment by RobertBColton** [comment] 2017-09-29 18:37
It is actually just the same as GameMaker. Basically, when you pick a shape the mask and pixel perfect doesn't apply. And if you pick the mask/pixel perfect route then the shape doesn't matter. As far as the UI guys, that's actually a change that would be nice to have in LateralGM (the IDE). When you select different shapes it should be showing you them instead of a rectangle, like GameMaker's IDE. It should also be disabling the mask options when they aren't applicable. I believe I was going to make this change before, because GameMaker disables them too, but I was afraid to because I thought people might still want to edit them. Basically, because the sprite_* functions will still return the correct values, even if they don't apply. I felt that people may be interested in making a special use of the variables in such cases.

You can file a request for that feature to be added over on LGM's tracker:
https://github.com/IsmAvatar/LateralGM

Since you have another ticket for the hWnd issue, I am going to close this one because we can't reproduce any issue with the site. For future reference, website issues also have their own trackers:
https://github.com/enigma-dev/Forum-Themes
https://github.com/enigma-dev/EDC
https://github.com/enigma-dev/Simple-Machines-GitHub-Issues
https://github.com/enigma-dev/Site

Please be conscientious of which tracker you submit an issue too. If you are still having problems signing up to the website at this point, please let us know and try to get a screenshot that demonstrates the error message on the signup page.

**Closed by RobertBColton** 2017-09-29 18:37 UTC
