### ISSUE TITLE
Undefined variable error using object-local variables for some math functions in Scripts

### ISSUE THREAD

**Issue by BPzeBanshee** [enigma-dev/enigma-dev#914] opened 2014-12-29 09:31 UTC
Example project file: https://www.dropbox.com/s/17vq0m3u78phgf7/Test3.gmk?dl=0
Full compile log (important part in example comments anyway): http://pastebin.com/1XBn9sjL

I have commented out several math functions which generate an error when using a variable defined in the calling object of the script rather than the script itself. GM8.0 Pro doesn't complain but ENIGMA reports variable was not declared in this scope only with the following functions:

choose
min
max
mean
median

Looks like something went wrong in the multiple-arguments part, although I'm no C++ expert.

**Comment by RobertBColton** [comment] 2016-04-24 19:36
Closing because this is an exact duplicate of #214

**Closed by RobertBColton** 2016-04-24 19:36 UTC
Labels: Bug, Compile, Confirmed, Parsing, Reproducible, Universal System
