### ISSUE TITLE
Graphics card inconsistencies.

### ISSUE THREAD

**Issue by SuperRiderTH** [enigma-dev/enigma-dev#671] opened 2014-03-17 12:51 UTC
Using surfaces in GL1 on different graphics cards causes different results. (Or surfaces just don't work on Intel HD Graphics.)
Using a computer with an Nvidia graphics card draws surfaces, (however they are upside down but that is not really a problem for me atm.) however using a laptop with Intel HD Graphics 4000 causes the surface to not draw.

It also appears that views are different between the two.

**Comment by RobertBColton** [comment] 2019-05-07 20:34
Closing as a duplicate of #658 and possibly #1705. Once these issues are fixed, a CI regression test would be really nice to keep it working forever thereafter. Also, the fallback discussed would be nice as well, even though D3D support has gotten a lot better in master. Pixel buffer objects (mentioned in #141) are also a good fallback for when even the extension is not supported in OpenGL 1.1.

**Closed by RobertBColton** 2019-05-07 20:35 UTC
Labels: Bug, Graphics
