### ISSUE TITLE
Surfaces drawn at incorrect position and size.

### ISSUE THREAD

**Issue by sorlok** [enigma-dev/enigma-dev#861] opened 2014-11-09 06:00 UTC
Consider the following, in a room that is 800x600 (on Linux, OpenGL1). Sample game:
https://drive.google.com/file/d/0B1P7NepPcOslbEg5WDBnTnVkbDA/view?usp=sharing

```
//In create():
global.mysurf = surface_create(700, 500);

//In draw():
surface_set_target(global.mysurf);
draw_set_color(c_black);
draw_rectangle(0, 0, 700, 500, false);
draw_set_color(c_blue);
draw_rectangle(10, 10, 690, 490, false);
draw_set_color(c_red);
draw_rectangle(20, 20, 680, 480, false);
surface_reset_target();
draw_surface(global.mysurf, 10, 10);
```

In GM:S, this draws a nice nested rectangle at (10,10), like so:
http://i.imgur.com/t9i9zhl.png

In ENIGMA, it looks very different:
http://i.imgur.com/BkEhRzK.png

For one, the (x,y) position the surface is drawn AT is way off. For another, the size of the surface is also wrong.

Any idea what might be causing this? Note that this issue affects any game that uses surfaces extensively for drawing, such as Spelunky.

**Comment by fundies** [comment] 2017-12-25 14:15
edited title to be a bit more descriptive

**Comment by RobertBColton** [comment] 2019-05-07 20:10
Closing as a duplicate of #658.

**Closed by RobertBColton** 2019-05-07 20:10 UTC
Labels: Confirmed, Graphics, Reproducible
