### ISSUE TITLE
sprite_assign with free_texture=true corrupts in some cases.

### ISSUE THREAD

**Issue by sorlok** [enigma-dev/enigma-dev#615] opened 2014-01-15 21:13 UTC
In certain cases, sprite_assign will corrupt something graphics-related if the value for parameter free_texture is true (the default). 

I noticed this issue in Iji, and have trimmed down a test case to the following:
https://drive.google.com/file/d/0B1P7NepPcOsld3M1RlBYVk55ZUk/edit?usp=sharing

There is one (large) map, which contains only one object. That object calls sprite_assign on crate(). If you comment out that line, the image shown will be a slightly different shade of blue. Given that sprite_assign occurs multiple times in Iji, the end result is far more wild:
http://imgur.com/Od9MX3G

I'm still narrowing this down; no idea what's causing a seemingly-harmless call to sprite_assign to wreak so much havoc. Some other test cases I wrote from scratch do not feature this problem.

**Comment by fundies** [comment] 2020-05-13 17:37
@sorlok do you have the example game still? I refactored sprite stuff recently and am curious if this is still an issue

**Comment by RobertBColton** [comment] 2020-05-13 19:09
This one shouldn't exist anymore, it was caused by us actually erasing a texture from the texture array, instead of just nulling it. We don't do that anymore, so it should be fixed now.
https://github.com/enigma-dev/enigma-dev/blob/9cf788d3f3ebd8456a0d51589889f110e69b3b3d/ENIGMAsystem/SHELL/Graphics_Systems/General/GStextures.cpp#L138

**Comment by fundies** [comment] 2020-05-13 23:28
so close it thanks

**Comment by RobertBColton** [comment] 2020-05-13 23:39
Yeah, I am quite certain this was actually resolved, the erasing from the vector sorlok reported is gone now. I totally misunderstood him originally and this issue got derailed into us talking about how to store the metadata. We've already established AssetArray and how we should handle assigning/creating/deleting resources as well as storing metadata.

For example, our `GLTexture` inherits our generic `Texture` these days.
https://github.com/enigma-dev/enigma-dev/blob/9cf788d3f3ebd8456a0d51589889f110e69b3b3d/ENIGMAsystem/SHELL/Graphics_Systems/OpenGL-Common/textures_impl.h#L31

Texture deletion now involves deleting the peer, then assigning nullptr to where that texture was.
https://github.com/enigma-dev/enigma-dev/blob/9cf788d3f3ebd8456a0d51589889f110e69b3b3d/ENIGMAsystem/SHELL/Graphics_Systems/General/GStextures.cpp#L136

No textures are moved or reallocated during deletion.

**Closed by RobertBColton** 2020-05-13 23:39 UTC
Labels: Bug, Graphics
