### ISSUE TITLE
Cant build a Simple game "error: Unknown function or script `toString'"

### ISSUE THREAD

**Issue by RodrigoCard** [enigma-dev/enigma-dev#1004] opened 2016-08-26 02:06 UTC
Hello there!
This is the first time I am trying enigma-dev so I can port an old game to linux

I am trying to build [this](https://dl.dropboxusercontent.com/u/14890209/downloads/Catch_the_Clown.gmk) test game (starting small) with the latest version 5ef6525

```
Building for mode (0)
Cleaning up from previous executions
 - Cleared parsed objects
 - Cleared room entries
 - Cleared shared locals list
 - Cleared event info
Loading shared locals from extensions list
Location in memory of structure: 0x7f71880c42f0
Copying resources:
Copying sprite names [2]
Copying sound names [0]
Copying background names [0]
Copying path names [0]
Copying script names [0]
Copying shader names [0]
Copying font names [1]
Copying timeline names [0]
Copying object names [2]
Copying room names [1]
Copying constant names [0]
SYNTAX CHECKING AND PRIMARY PARSING:
0 Scripts:
"Linking" scripts
`Linking' 0 scripts and 0 timelines in 0 passes...
Completing script "Link"
Done.
Completing timeline "Link"
Done.
2 Objects:
 obj_clown: 12 events: 
  Event[0]:   Parsing 1 sub-events:
Check `obj_clown::create...Syntax error in object `obj_clown', Create event:0:
Line 15, position 41 (absolute 384): Unknown function or script `toString'
```

Thanks for this nice piece of software and thanks for the help :)

**Comment by faissaloo** [comment] 2016-08-26 08:08
Temporary fix is to replace line 22 in enigma-dev/ENIGMAsystem/SHELL/SHELLmain.cpp with:
```
#ifndef JUST_DEFINE_IT_RUN
  #include <string>
#else
  #define _GLIBCXX_STRING 1
  template<typename T, typename traits = int> class basic_string {};
  typedef basic_string<char> string;
#endif
```
Duplicate of #978 it's an issue caused by newer versions of GCC.

**Comment by RodrigoCard** [comment] 2016-08-27 08:07
Thanks, it did the trick.

**Comment by RodrigoCard** [comment] 2016-08-27 08:08
by the way, this issue is caused by GCC, but is it GCC's bug or enigma's?

**Comment by faissaloo** [comment] 2016-08-27 08:26
I'm guessing GCC, because I've seen it turn up in some other people's projects to, but I'm not 100% sure.

**Comment by RobertBColton** [comment] 2016-08-29 06:23
Good work faissaloo. I am closing this as you indicated it is a duplicate. FYI, I am really swamped moving and starting the semester so I am really trying to get on here more.

**Closed by RobertBColton** 2016-08-29 06:23 UTC
