### ISSUE TITLE
Enigma crashes on game compile.

### ISSUE THREAD

**Issue by ghost** [enigma-dev/enigma-dev#946] opened 2015-08-31 18:55 UTC
**As per request this issue has been moved from the LateralGM tracker to the Enigma tracker.**

Original issue text:
*So Engima keeps crashing with this message when I try to compile my game:
Restarting it doesn't seem to help. However making a new blank game with just a room causes no crashes.*

*Operating System: Windows 8.1
Version: 6.3
Architecture: x86*

*Java Vendor: Oracle Corporation
Version: 1.8.0_31*

*Available processors (cores): 4
Free memory (bytes): 212019776
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259522560*

*File system root: C:\
Total space (bytes): 948908847104
Free space (bytes): 271032102912
Usable space (bytes): 271032102912*

*File system root: D:\
Total space (bytes): 26843541504
Free space (bytes): 23842299904
Usable space (bytes): 23842299904*

*File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0*

*File system root: H:\
Total space (bytes): 15539896320
Free space (bytes): 15530426368
Usable space (bytes): 15530426368*

*Stack trace:*

*java.lang.Error: Invalid memory access
at com.sun.jna.Native.invokeInt(Native Method)
at com.sun.jna.Function.invoke(Function.java:383)
at com.sun.jna.Function.invoke(Function.java:315)
at com.sun.jna.Library$Handler.invoke(Library.java:212)
at com.sun.proxy.$Proxy0.compileEGMf(Unknown Source)
at org.enigma.EnigmaRunner$CompilerThread.run(EnigmaRunner.java:671)*

As per the suggestions by @JoshDreamland I removed all fonts and I also removed the one blank sprite that the game had incase these were giving Enigma the headache. The same crash message still appeared, so I reloaded the game file and as a hunch I removed all timelines. (I did this because in the past I had had a lot of problems with timeline not working and Enigma not telling me of any problems with them). And the game successfully compiled again.

So here is a link to the game (as a .gmk) with the error (with the timelines and fonts): http://puu.sh/jVijz/98078c002f.gmk
However upon trying to narrow down the error by deleting 1 of my 2 timelines I found that no matter which 1 of the 2 timelines you delete the game will run as normal. 

Well anyway, this could be completely wrong but that's what I think is happening.

Also I don't know if this is really relevant but the progress window that pops up during th compile stops here: https://puu.sh/jVk6Y/67f94a3af9.png

**Comment by RobertBColton** [comment] 2016-04-20 22:26
This seems to be a duplicate of an open plugin issue. This is the only issue with ENIGMA I have no yet managed to figure out or reproduce. If someone can offer a way of reproducing this on my machine I may be able to fix it or find a solution.
https://github.com/enigma-dev/enigma-dev/issues/946

**Comment by RobertBColton** [comment] 2016-09-13 20:45
Closing as a duplicate of an open plugin issue. Would appreciate additional feedback on the plugin tracker issue.

**Closed** 2016-09-13 20:44 UTC
Labels: Compile Error, Confirmed, Exception, Plugin
