### ISSUE TITLE
draw_sprite crashes when given negative image_index

### ISSUE THREAD

**Issue by Gamer2014** [enigma-dev/enigma-dev#865] opened 2014-11-12 06:10 UTC
Received this message when trying to run a game:

 an unhandled win32 exception occurred in egm5767977426534898993.exe
0xC0000005: Access violation reading location 0x75422e80. 

Link to output_log.txt: 

http://pastie.org/9713506

**Comment by RobertBColton** [comment] 2016-09-09 20:25
@TheExDeus to make draw_sprite wrap -2 around you should make the function take unsigned/size_t as the subimage index parameter. Then -1 would actually wrap around and be like UNSIGNED_INT_MAX and -2 would be that minus 1 due to the way the two's complement works. This should be resolved at the same time as #228 which I may do later on tonight.

**Comment by RobertBColton** [comment] 2016-09-14 04:23
I am going to test all of the issues in this ticket so we can close it.

I tested the following in GMS, GM 5, and ENIGMA where it behaved the same in each.
```gml
direction = -640;
show_message(string(direction)); // shows 80
direction = 640;
show_message(string(direction)); // shows 280
```

**Comment by fundies** [comment] 2017-12-25 14:20
This is undefined behavior even between GM's versions. I'm in favor of this crashing and asserting and error in debug mode but if you can chose any of the other behaviors, note it somewhere and close this.

**Comment by RobertBColton** [comment] 2017-12-25 18:54
There are only two issues left:
1. Assign a sprite to object, set image_index to -2 in create event, call draw sprite passing any negative value for the subimage parameter. This results in a crash only when the sprite has more than 1 subimage.
2. Don't assign a sprite, doesn't matter what you set image_index to (or whether you even set it at all), draw the sprite with negative subimage index. This just draws the first frame of the sprite with no animation.

These are the GameMaker 5 and Studio results:
1. No crash, just draws the sprite with animation (if more than one subimage).
2. No crash, just draws the sprite with animation (if more than one subimage).

FIx these two crashes in ENIGMA and we can close this.

**Comment by RobertBColton** [comment] 2018-05-23 21:14
We may want to backtrack our thinking, because by not supporting this, we by extension do not support an animated `cursor_sprite` for the global variable or the Drag & Drop action as I discovered in #1240.

**Comment by fundies** [comment] 2020-05-13 17:54
@RobertBColton I cannot repro this on master can we close it?

**Comment by RobertBColton** [comment] 2020-11-15 03:54
I split the image index anomalies out into their own issue #2154 without knowing it, but there is one new one in that ticket. The original issue here is just that a negative image_index will crash, which it still does. I don't really know if that makes sense since #2157 where we still support negative subimage index. All we'd need to do there is take the absolute value of `image_index` to fix it literally everywhere and just close this ticket.

**Comment by RobertBColton** [comment] 2020-11-15 04:40
So I just realized after looking over #1240 the one issue I still see doesn't have anything to do with the image_index being negative at all. With respect to drawing `cursor_sprite` in the redraw code, there's no current instance in scope as it is fired from the main event loop. That leads to a crash trying to read the `image_index` local of a null pointer.

**Comment by JoshDreamland** [comment] 2020-11-15 05:21
This seems to be fixed, or is no longer reproducible.

**Closed by JoshDreamland** 2020-11-15 05:21 UTC
Labels: Crash, Graphics

**Comment by RobertBColton** [comment] 2020-11-15 05:38
I printed `return -6 % spr2d.SubimageCount();` which gave me 2, so it seems C++ modulo operator no longer keeps the sign? That would explain why it's not reproducible now.

**Comment by RobertBColton** [comment] 2020-11-15 15:32
@JoshDreamland I found out why it no longer crashes in online C++ compiler. If the modulus is signed and the number is negative, you get a negative result, but if the modulus is unsigned or size_t you get a positive result because the negative number is implicitly converted to unsigned. So it's the fact that fundies implemented a `Sprite::SubimageCount` that returns `size_t` which we use as the modulus that this issue is no longer reproducible.
https://github.com/enigma-dev/enigma-dev/blob/2fb4c5c9118d9865574f593c95429961606cdd72/ENIGMAsystem/SHELL/Universal_System/Resources/sprites_internal.h#L63

```cpp
#include <iostream>

using namespace std;

int main()
{
    int count1 = 4;
    size_t count2 = 4;
    cout <<"Signed " << (-5 % count1) << ' ' << (-6 % count1) << std::endl;
    cout <<"Unsigned " << (-5 % count2) << ' ' << (-6 % count2) << std::endl;

    return 0;
}

/* RESULTS
Signed -1 -2                                                                                                                                   
Unsigned 3 2   
*/
```

**Comment by RobertBColton** [comment] 2020-11-15 15:42
Yeah this issue is done, having a negative image_index was never documented _anywhere_ in GameMaker. The only thing that was documented was that -1 to draw_sprite will use image_index, which it correctly does in ENIGMA. I see no reason for anybody to ever have a negative image_index and try to use it, it's just undefined. In fact, the negative image_index issue was filed against GMSv1.4 too, and apparently never fixed.
https://bugs.yoyogames.com/view.php?id=11501
