### ISSUE TITLE
Cannot compile games or use ENIGMA in Fedora 25

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1048] opened 2017-04-19 23:17 UTC
I've followed the build instructions [from here](http://enigma-dev.org/docs/Wiki/Install:Linux). I can compiling everything just fine in Fedora 25, and LateralGM loads as long as I use the x86 Open JRE. However, I cannot compile anything, nor by LateralGM nor using the Terminal.

Those are the 2 error screens in LateralGM:
![lateralgm_error1](https://cloud.githubusercontent.com/assets/16482463/25206172/b207eb7e-253c-11e7-9dfd-2c1c0c9e9b6f.png)
![lateralgm_error2](https://cloud.githubusercontent.com/assets/16482463/25206174/b2126cc0-253c-11e7-8af4-2f22270b5dc1.png)

This is the error report:
```
Operating System: Linux
Version: 4.10.10-200.fc25.x86_64
Architecture: i386

Java Name: OpenJDK Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_121

Available processors (cores): 8
Free memory (bytes): 65288448
Maximum memory (bytes): 954466304
Total memory available to JVM (bytes): 82313216

File system root: /
Total space (bytes): 140975374336
Free space (bytes): 83744063488
Usable space (bytes): 76559220736

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (linux-x86/libcompileEGMf.so) not found in resource path ([file:/home/morello/enigma-dev_meme2/plugins/enigma.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:248)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:241)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:179)
```

And this is the error I get if I use the Terminal:
```
$ java -jar plugins/enigma.jar pkmn2.gmk
Loading lib files in /home/morello/enigma-dev_meme2/lateralgm.jar
01_move.lgl 02_main1.lgl 03_main2.lgl 04_control.lgl 
 05_score.lgl 06_extra.lgl 07_draw.lgl 
enigma: java.lang.NullPointerException: null
```
`libcompileEGMf.so` is inside the `enigma-dev` folder. No idea why it isn't finding it.
If theres any information missing, please tell.

**Comment by RobertBColton** [comment] 2017-09-30 02:47
Hi! Sorry I didn't get around to responding sooner. This issue may possibly be a duplicate of the following:
https://github.com/enigma-dev/enigma-dev/issues/944

We are working to solve the issue now. If you are still interested in getting ENIGMA running and haven't succeeded, it would be useful to know your GCC version. Otherwise, I am going to close this ticket for now and please let me know if you need anymore help. Thanks!

**Closed by RobertBColton** 2017-09-30 02:47 UTC
