### ISSUE TITLE
Can't compile anything without paths extension

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#1036] opened 2016-12-03 13:25 UTC
If you try to compile anything without the paths extension the following happens:
```
/home/faissaloo/.enigma/.eobjs/Linux/Linux/Run/Universal_System/planar_object.o: In function `enigma::propagate_locals(enigma::object_planar*)':
planar_object.cpp:(.text+0x2bc): undefined reference to `enigma_user::path_update()'
/home/faissaloo/.enigma/.eobjs/Linux/Linux/Run/Universal_System/loading.o: In function `enigma::initialize_everything()':
loading.cpp:(.text+0x1ab): undefined reference to `enigma::exe_loadpaths(_IO_FILE*)'
collect2: error: ld returned 1 exit status
Makefile:117: recipe for target 'compile_game' failed
make[1]: *** [compile_game] Error 1
make[1]: Leaving directory '/home/faissaloo/enigma-dev/ENIGMAsystem/SHELL'
Makefile:12: recipe for target 'Game' failed
make: *** [Game] Error 2
```

**Comment by RobertBColton** [comment] 2017-04-17 01:05
Closing as a duplicate of #456

**Closed by RobertBColton** 2017-04-17 01:05 UTC
