### ISSUE TITLE
Missing functions...... not member of 'enigma' error 

### ISSUE THREAD

**Issue by Hughtech** [enigma-dev/enigma-dev#1162] opened 2018-01-18 09:10 UTC
I'm writing some tutorials  for working in ENIGMA for LINUX and as I'm writing I'm also creating an example file. The one in particular is a 2D Breakout game which I will convert to 3D. The process is similar to GameMaker conversion of 'Veg Ninja' to Duck Shoot. 

 At the point of running the ball collision code with the wall objects, errors occur. 

![tutorial_error-screenshot](https://user-images.githubusercontent.com/19632613/35087773-c2918be2-fc07-11e7-8e2a-2b5159c849a4.png)

 If I use drag and drop, the same thing happens. I've tried other things like a 'reverse horizontal', same error; 'bounce against solid", same error.

**Comment by RobertBColton** [comment] 2018-01-18 09:17
These were regressions introduced by #1128 and I fixed them in #1147. Please cd into enigma-dev and then do a `git pull`. Let me know if that works.

**Comment by Hughtech** [comment] 2018-01-18 10:10
Wow! this response was fast! 👍 

As an experiment, I deleted my emiga-dev folder and replaced it with the one I have on my laptop. everything is now working fine now. 
I'm sorry i didn't know that it it had been fixed before. Guess I'll have to re-install again........but this time I'll do it on a different computer. All these problems are holding me up on doing some contributory work to the project. :)

**Comment by RobertBColton** [comment] 2018-01-18 10:15
Absolutely! It was actually a relatively simple fix, we changed the name of the include guard for the collisions object to match our styleguide (i.e. prefixed `ENIGMA_`) but not the usage:
https://github.com/enigma-dev/enigma-dev/pull/1147/files#diff-dede076b7147f44cf2a637af873a8aceR38

You may not be aware, but we are working on some big structural changes:
https://enigma-dev.org/forums/index.php?topic=2863.0

All of these are to improve the stability of the ENGINE. There is going to be more breaking changes in the coming weeks, but they will be minor and they will be to improve the engine overall. As regressions are found we will prioritize and address them. If an older version is working for you consistently, you should probably save a copy of it and work with it for a while.

**Comment by RobertBColton** [comment] 2018-01-18 10:50
Sorry, did not mean to confuse you, you _may_ close this, that's fine, it's already been fixed as I said.

**Closed by RobertBColton** 2018-01-18 10:50 UTC

**Comment by Hughtech** [comment] 2018-01-18 10:53
Yes I have heard of the changes being done, though what they are I don't know. To tell you the truth, after working with the project for a year, and taking into account my many years of working with Gamemaker,  I am very satisfied with your project. Are they some things that can be improved on? Yes but in my opinion this project surpasses Gamemaker in terms of execution, logic, and ease. The only 2 main issues I have as far as working on LINUX is concerned is working in 3D and using Shaders. But that is another matter altogether.
I hope that you can implement Dialog extensions for LINUX as they can only work in WINDOWS. 
I also hope that in your structuring, revamping, additions and so forth, ENIGMA doesn't come of as too much a clone of GameMaker, but remains as an **Alternative** to it.

**Comment by RobertBColton** [comment] 2018-01-18 11:11
Well the biggest part of it so far was basically this integration testing you see with AppVeyor and Travis (the green "passing" status badges on our README.md).

They look like this: [![Travis CI Build Status](https://travis-ci.org/enigma-dev/enigma-dev.svg?branch=master)](https://travis-ci.org/enigma-dev/enigma-dev/) [![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/4j4hklw0ned5wbys?svg=true)](https://ci.appveyor.com/project/enigma-dev/enigma-dev)

The way we used to develop the project was that a contributor would have to take their changes to the code around on different computers or virtual machines to make sure everything still works. A lot of people, even myself sometimes, were too lazy to do this and we ended up merging lots of broken changes frequently etc.

Now, with our new setup, if somebody changes something they can just open a regular git pull request and in about 30 to 45 minutes Travis and AppVeyor will tell us and them if their changes pass on Windows, Linux, and Mac respectively.

So, basically we've been automating a lot of the tedious work involved in changing the code/implementing new functions/fixing bugs, etc. It really has been going great and it's the reason I was able to have this regression you reported here fixed so quickly. I didn't even have to leave Windows to know that the fix would work! So a huge thanks to Travis and AppVeyor for offering this service free to open source projects.

Some other improvements that are side effects of the AppVeyor/Travis changes include the introduction of a native command line interface. We plan to add GMX to it soon, but for now it is the backbone of our AppVeyor/Travis builds. In the future, you will be able to execute this from a terminal and build a game with ENIGMA without an IDE and in a much faster time.
https://github.com/enigma-dev/enigma-dev/tree/master/CommandLine/emake

I hope this helps clarify why these improvements are, and will be, both substantial and extremely useful. We'll have more awesome things to share soon!

**Comment by Hughtech** [comment] 2018-01-18 11:21
Actually it explains a lot. goombert just posted in the forums about results of MAC testing involving the Travis/AppVeyor 'issue' and it prompted me to do some reasearch. Accordingly Travis is ranked the 3rd best to AppVeyor ranked at 11th, so that may be something to consider.

However, I fully understand now and quite agree that such a change would be much easier as I am also constantly, testing this an that on different machines especially when it comes to trouble-shooting for other LINUX users.
👍 👍

**Comment by faissaloo** [comment] 2018-01-18 11:53
@Hughtech Goombert is @RobertBColton btw

**Comment by Hughtech** [comment] 2018-01-18 11:55
My apologies!! :)
