### ISSUE TITLE
[suggestion] game_save and game_load

### ISSUE THREAD

**Issue by harmjanhaisma** [enigma-dev/enigma-dev#1015] opened 2016-09-10 16:28 UTC
I have a pretty old gm8.1 project that i want to compile, however, it makes use of game_save and game_load.
This is not yet in enigma.

**Comment by fundies** [comment] 2016-09-10 19:23
Game Save / Load are very complicated and probably aren't coming for a long time. I'd suggest writting your own saving / loading functios specific to your game using ini or json extensions

**Comment by RobertBColton** [comment] 2016-09-11 13:32
Hi, thank you for the suggestion! As fundies said it is often better to write custom save functionality for your game because the resulting save files will be much smaller. Also, this issue has been reported in the past. I must close this as it is a duplicate of #40 where Josh gave an in-depth explanation of how the functions may be implemented.

**Closed by RobertBColton** 2016-09-11 13:32 UTC
