### ISSUE TITLE
User alphas are not clamped

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#956] opened 2016-02-15 15:55 UTC
image_alpha=1+n when the image is drawn, looks like it's looped back to 0+n, even though the value is still 1+n. So for example, 1.1 will look almost completely transparent and 2 will look solid with 1.5 looking semi-transparent when any value above 1 should be treated the same as if it were 1.

**Comment by faissaloo** [comment] 2016-04-25 19:21
This seems to be caused by glColor4ub() being given an alpha value that when multiplied by 255, overflows, so we'd have to clamp it before multiplying it to prevent the alpha from looping like this.

**Comment by faissaloo** [comment] 2016-04-27 12:52
This seems to a duplicate of #757.
Robert said:  
> I am not going to add a check for every color  

But also said  
>You should have let Josh and Harri weigh in and we'd make a mutual decision as a community. I don't make the ultimate say in anything.  

So should I just close this or not?

**Comment by JoshDreamland** [comment] 2016-04-28 15:23
It's worth keeping this bug open. I'd sooner close #757, because this bug is more precise.

This is certainly not something we want to handle for each vertex in a shader; it's just a waste. It's not as big a waste as Robert seems to think, thanks to parallelization, but it's still pointless to do that.

What I'd do instead is clamp image_alpha when we go to render your sprite for you—that is, in our default draw event implementation, pass image_alpha to `clamp` along with 0 and 1 (this is the same as `median(image_alpha, 0, 1)`).

If that's not good enough, I'd recommend a setter, which ENIGMA doesn't support. In that case, we'd probably close this as infeasible, but add it to a future milestone for if/when ENIGMA has more capable language bindings.

**Comment by faissaloo** [comment] 2016-04-28 20:08
I think we should go with the setter idea, when it is indeed possible. Clamping image_alpha before drawing with it would only fix one prescence of the issue.

**Comment by RobertBColton** [comment] 2016-04-28 20:25
My vote goes for a setter, why can't we have one Josh?

**Comment by faissaloo** [comment] 2016-04-28 21:21
We can't have image_alpha ever actually hold the clamped value, some code might rely on image_alpha having a higher value than 1, granted, that behaviour isn't really used for much, it is still a thing that can be and has been done, especially for animations, to reduce the amount of variables needed, and if we were to just disregard that then we'd be left with another problem of the same calibur as this. The clamped value should only every be used internally.

**Comment by RobertBColton** [comment] 2016-04-29 00:34
You are correct, thanks for mentioning that. I just tested setting it to 5 in the create event and drawing it in the draw event in GMS and it stayed as 5.

**Comment by JoshDreamland** [comment] 2016-04-29 14:53
It's not that we can't have a setter—it's that creating one is not convenient. It's ugly, it increases code and compile size, and it's relatively inefficient. I made it somewhat more convenient by creating `multifunction_variant`. You can extend that to achieve what you want. It's not pretty, but it is viable, I suppose.

As for the behavior of computations on `image_alpha` that go outside `[0, 1]`... I really don't care. The `image_alpha` variable is one of those weird artifacts of GM5 and earlier, where we set `draw_color` instead of using `draw_set_color`. It wouldn't surprise me to learn that GM8 clamps `image_alpha` upon set; it's not supposed to be a normal variable.

But still, there's not much benefit to breaking that. I still believe our best course of action is to wrap internal engine use of `image_alpha` in a `clamp`. It's not consistently more or less efficient than using a `multifunction_variant` setter (question is whether you read or write more often), and it's less likely to break existing code.

**Comment by RobertBColton** [comment] 2016-04-29 16:38
Well the other good news Josh is that I did move all of our drawing functions such as draw_sprite_* etc into the general system using the primitive vertex drawing functions. So I basically bootstrapped ENIGMA's graphics system.
https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Graphics_Systems/General/GSstdraw.cpp#L165
As you can see it uses draw_get_alpha to do all the internal rendering. We could clamp inside draw_get_alpha or we could clamp inside all the primitive vertex functions.

**Comment by RobertBColton** [comment] 2016-04-29 16:55
Actually I just tried this in GMS and I guess it actually works exactly the same.
```gml
draw_set_alpha(5);
show_message(draw_get_alpha());
```

**Comment by faissaloo** [comment] 2016-04-29 17:09
Why not just clamp draw_set_alpha() for the functions that don't have their own alpha specified? it would mean that you'd only have to clamp it once rather than clamping it every time draw_get_alpha() is used.

**Comment by RobertBColton** [comment] 2016-04-29 18:20
Yes that's an excellent point. I will go and test draw_set_alpha after bit here in GMS again to see if it does the clamping visually to verify that it's not draw_get_alpha doing the clamping. It seems like with the revamp of the graphics system I did that this is a lot easier to fix actually. Would like to know what @JoshDreamland thinks about clamping in draw_set_alpha?

**Comment by RobertBColton** [comment] 2016-04-29 23:20
I can confirm this must be the case that draw_set_alpha does the clamping because I just tested the following code in GMS and the drawn objects appeared to be fully transparent with the alpha clamped to 1.
```gml
draw_set_alpha(1.5);
draw_circle(50, 50, 50, false);

draw_sprite_ext(sprite0, 0, 150, 50, 1, 1, 0, c_white, 1.5);
```

**Comment by JoshDreamland** [comment] 2016-04-29 23:45
I don't have a problem with clamping it in draw functions that accept alpha.

**Comment by faissaloo** [comment] 2016-04-30 12:03
@RobertBColton No, for two reasons:  
  
- I found another bug, #967  
- The original issue that I described in OP concerns image_alpha, which is just one place where this bug is present, clamping draw_set_alpha() has no effect.

**Comment by faissaloo** [comment] 2016-04-30 12:11
draw_set_alpha() is apparently already being clamped so we'll only need to clamp functions that take alpha from other sources: https://github.com/enigma-dev/enigma-dev/blob/d9746dfc6d557c4c22c8bd8cf24e02e3272eade0/ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLcolors.cpp#L76

**Comment by RobertBColton** [comment] 2016-04-30 17:04
I guess somewhere we decided to make alpha a default argument for all sprite functions.
https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.h#L27

Either way, yes I kind of figured that already. Either way the solution is to go through all drawing functions which take an alpha parameter and do "alpha = bind_alpha(alpha);" and then it should work like GMS.

That will fix the image_alpha problem too because it is only used in draw_self. I tested the following in GMS and it appears that draw_set_alpha has no effect on draw_self.
```gml
//image_alpha = 0.5;
draw_set_alpha(0.5);
draw_self();
```

**Comment by RobertBColton** [comment] 2016-05-30 17:40
Please see my comments on #967 as I was unaware of a change made by @polygoned where he made every drawing function take a color and alpha. So we have to put bind_alpha in every one of these functions, but not multiply it to draw_set_alpha, we need to default it to the set alpha and color in the header.

This will be the convention:
```c++
// this one does not take color and alpha in GM so the extra parameters in ENIGMA should default
// to the set color and alpha
void draw_sprite(int spr, int subimg, gs_scalar x, gs_scalar y, int color = draw_get_color(), gs_scalar alpha = draw_get_alpha());
// functions that do take color and alpha in GM should simply leave the default arguments to c_white
// and 1.0 for the alpha, draw_sprite_ext is one of those functions
void draw_sprite_ext(int spr, int subimg, gs_scalar x, gs_scalar y, gs_scalar xscale = 1, gs_scalar yscale = 1, double rot = 0, int color = 16777215, gs_scalar alpha = 1);
```

**Closed** 2016-07-02 20:04 UTC
Labels: Bug, Confirmed, Graphics, Reproducible
