### ISSUE TITLE
Error when compiling ENIGMA on OS X

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1059] opened 2017-06-09 17:45 UTC
I'm getting the following error when trying to compile ENIGMA on OS X.

```
compiler/components/parse_and_link.cpp:67:56: error: use of overloaded operator
      '<<' is ambiguous (with operand types 'ideprint' and 'size_type'
      (aka 'unsigned long'))
    edbg << "Parsed `" << es->scripts[i].name << "': " << scripts[i]->obj.locals.size()...
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./backend/ideprint.h:29:13: note: candidate function
  ideprint &operator<< (int16_t x);
            ^
./backend/ideprint.h:30:13: note: candidate function
  ideprint &operator<< (int32_t x);
            ^
./backend/ideprint.h:31:13: note: candidate function
  ideprint &operator<< (int64_t x);
            ^
./backend/ideprint.h:32:13: note: candidate function
  ideprint &operator<< (uint16_t x);
            ^
./backend/ideprint.h:33:13: note: candidate function
  ideprint &operator<< (uint32_t x);
            ^
./backend/ideprint.h:34:13: note: candidate function
  ideprint &operator<< (uint64_t x);
            ^
./backend/ideprint.h:35:13: note: candidate function
  ideprint &operator<< (char x);
            ^
./backend/ideprint.h:36:13: note: candidate function
  ideprint &operator<< (unsigned char x);
            ^
./backend/ideprint.h:37:13: note: candidate function
  ideprint &operator<< (double x);
            ^
compiler/components/parse_and_link.cpp:98:112: error: use of overloaded operator
      '<<' is ambiguous (with operand types 'ideprint' and 'size_type'
      (aka 'unsigned long'))
  ...edbg << "Parsed `" << es->timelines[i].name <<", moment: " <<es->timelines[i].moments[j].stepNo << "': " << tlines.back()->obj.locals.size()...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./backend/ideprint.h:29:13: note: candidate function
  ideprint &operator<< (int16_t x);
            ^
./backend/ideprint.h:30:13: note: candidate function
  ideprint &operator<< (int32_t x);
            ^
./backend/ideprint.h:31:13: note: candidate function
  ideprint &operator<< (int64_t x);
            ^
./backend/ideprint.h:32:13: note: candidate function
  ideprint &operator<< (uint16_t x);
            ^
./backend/ideprint.h:33:13: note: candidate function
  ideprint &operator<< (uint32_t x);
            ^
./backend/ideprint.h:34:13: note: candidate function
  ideprint &operator<< (uint64_t x);
            ^
./backend/ideprint.h:35:13: note: candidate function
  ideprint &operator<< (char x);
            ^
./backend/ideprint.h:36:13: note: candidate function
  ideprint &operator<< (unsigned char x);
            ^
./backend/ideprint.h:37:13: note: candidate function
  ideprint &operator<< (double x);
            ^
3 warnings and 2 errors generated.
make: *** [.eobjs/./compiler/components/parse_and_link.o] Error 1
```

Steps to reproduce:
1. Clone the repository
2. `cd compilerSource && make clean && make`

LateralGM seems to be running fine - though it obviously can't compile games because its lacking ENIGMA.

**Comment by faissaloo** [comment] 2017-06-09 22:23
What version of GCC are you using? Go to a terminal and type ```gcc -v``` to check

**Comment by 9Morello** [comment] 2017-06-10 02:20
Here is the output of `gcc -v`:
```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by faissaloo** [comment] 2017-06-10 11:39
This seems to me like a duplicate of https://github.com/enigma-dev/enigma-dev/issues/1001  
  
Try compiling this fork instead of the master repository: https://github.com/enigma-dev/enigma-dev/pull/1011

**Comment by 9Morello** [comment] 2017-06-11 15:24
@faissaloo That branch compiles ENIGMA, but I can't run any games I compile with it. Tried with a  new game with one object and got this output:

```
/Users/Morello/enigma-dev/MacOS/build/Release/EnigmaXcode.app/Contents/MacOS/EnigmaXcode ; exit;
Current working dir: /Users/Morello/enigma-dev/MacOS/build/Release/EnigmaXcode.app
2017-06-11 12:22:38.713 EnigmaXcode[17958:51321] Unable to load nib file: MainMenu, exiting
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

```

**Comment by faissaloo** [comment] 2017-06-11 18:33
Try exporting the game and running it manually

**Comment by 9Morello** [comment] 2017-06-14 17:43
Thanks, I didn't have the time to test it those days but I'll asap and post the result here.

**Comment by 9Morello** [comment] 2017-06-27 12:52
@faissaloo Sorry for taking so long. I just tried exporting the game and running it manually and it didn't work. The app instantly crashes before its window appears.

**Comment by faissaloo** [comment] 2017-06-27 14:39
Can you go into the .app bundle and find the actual executable and run it from a terminal so we can see the output?

**Comment by RobertBColton** [comment] 2017-10-01 06:58
Closing this as the issue hasn't had any updates in a while and it does look as though he got ENIGMA building, though not running. The issue also seems to be a duplicate of other issues (namely #1001). If there's anything new on this issue please discuss it there. If you discover any new and unrelated issues, please post separate tickets for those. Thanks!

**Closed by RobertBColton** 2017-10-01 06:58 UTC
