### ISSUE TITLE
draw_background on surface is offset by 1 on x,y and scaling bug

### ISSUE THREAD

**Issue by sssstest** [enigma-dev/enigma-dev#244] opened 2013-06-26 22:57 UTC
Image data if offset for sprites copied from surface (draw of background).

```
mysurface = surface_create(2000, 2000);
surface_set_target(mysurface);
draw_clear_alpha(c_red, 1);
draw_background(bkg,0,0);
surface_reset_target();
spr=sprite_create_from_surface( mysurface, 0, 0, 64, 64, 0, 0, 0, 0);
```

If you draw a solid background image you will see red border on top and left. When you draw the sprite you see the image data copied from surface is offset by +1 on x and y, cropping lower and right pixels. Using draw_background(bkg,-1,-1); fixes the problem or using sprite_create_from_surface( mysurface, 1, 1,) works.

Another problem is that if the surface size is close to the background size then the background is scaled down a couple pixels. You have to use a surface size maybe 3\* the size of the background to not scale the background.

I think the problem isn't in sprite_create_from_surface using glReadPixels. I think it is in draw_background or something it calls.

**Comment by RobertBColton** [comment] 2019-05-07 18:42
Closing as a duplicate of #658 where TheExDeus goes into more detail about the cause of the issues.

**Closed by RobertBColton** 2019-05-07 18:42 UTC
Labels: Bug
