### ISSUE TITLE
[Linux] Fullscreen doesn't work (!!)

### ISSUE THREAD

**Issue by mikeypro83** [enigma-dev/enigma-dev#2109] opened 2020-08-11 21:57 UTC
OS: Ubuntu 20.xx

Issue:
 Using 'Let F4 toggle fullscreen' does nothing.
 Using the 'Allow player to resize window' does not let user to resize the window
 'Start in fullscreen' does nothing.

Also to further the point: Cannot force fullscreen or adjust window size from Ubuntu GUI, can only minimize, unminimize and drag the window.

Using the script function window_set_fullscreen works as intended as a side note.

**Comment by time-killer-games** [comment] 2020-08-12 01:56
I'm having these problems as well. Someone must've broke lateralGM's hymen right in the pussy.

**Comment by time-killer-games** [comment] 2020-08-12 02:02
@JoshDreamland get rid of this unconfirmed bullshit tag there are already several bugs that have been confirmed and no one is caring enough to remove the tag on them it makes the tag useless because before you know it everything will have that tag.

**Comment by RobertBColton** [comment] 2020-08-12 02:11
This is a confirmed LGM regression that 1.8.160 introduced. It looks like save on the game settings frame was completely broke. If you guys want to please move the issue over there for me I will look into it later.

**Comment by RobertBColton** [comment] 2020-08-16 01:32
Closing as resolved in LGM v1.8.184 which is available for download.
https://github.com/IsmAvatar/LateralGM/commit/2bb31d00328c4dea6d341c6152f3760f71543709
https://github.com/IsmAvatar/LateralGM/releases/tag/v1.8.184

**Closed by RobertBColton** 2020-08-16 01:32 UTC
Labels: Double Confirmed

**Comment by mikeypro83** [comment] 2020-08-16 01:56
Wahoo! 

Sent from Yahoo Mail on Android 
 
  On Sat, Aug 15, 2020 at 7:32 PM, Robert Colton<notifications@github.com> wrote:   


Closed #2109.
