### ISSUE TITLE
window_*_fullscreen() functions break on room change

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#1549] opened 2019-02-16 14:19 UTC
Decided to give [xor](https://github.com/faissaloo/xor) a compile today.  
When in the main game if you hit escape, go to options and enable full screen then go back to the main menu the room will look stretched, if you go to the options here and try to disable fullscreen you will find that you cannot.  
This functionality is controlled by the following piece of code:  
`window_set_fullscreen(not window_get_fullscreen())`

**Comment by JoshDreamland** [comment] 2019-02-16 14:23
This sounds like two bugs. Robert was playing with window scaling not long ago... I thought he'd fixed it. And I thought I fixed `window_set_fullscreen` on Linux, and then Robert followed suit on Windows.

Does `window_set_fullscreen(0)` work for you?

**Comment by faissaloo** [comment] 2019-02-16 14:30
Calling window_set_fullscreen(0) causes the scaling to go funny and the get routine is still telling me it's fullscreen. I'm on Ubuntu 18.04.

**Comment by RobertBColton** [comment] 2019-02-16 14:55
I thought I fixed it and the window centering too, but to be honest with you, I was probably just throwing water on the fire. It's been acting quite funny since we did accept fundies SDL, but I kind of kept my mouth quiet assuming that the elimination of redundant code would eventually improve the situation for all of the platforms. Nobody has just taken up the business of getting them *perfect*, which is why I've left some of the reported issues open by TKG.

**Comment by JoshDreamland** [comment] 2019-02-16 17:36
Okay, that's really weird... if `window_get_fullscreen` is reporting that it's fullscreen, it has the fullscreen atom set on the window. Your window manager should be presenting it in fullscreen... Maybe the remove function is setting it to some null value that I'm not checking for.

I don't understand why scaling the damned view to fit proportionally in a window is so hard. Maybe I'll take a look later; right now, I'm sorting something else.

**Comment by faissaloo** [comment] 2019-02-16 19:16
It is *presenting* it in fullscreen, `window_set_fullscreen(0)` just makes the scaling weird, it doesn't stop it from being fullscreen.

**Comment by RobertBColton** [comment] 2019-02-16 20:51
Putting related issues #1069, #1083, #1084 here so they don't all get lost.

**Comment by RobertBColton** [comment] 2019-02-16 20:55
@faissaloo The room switching/window code that you specifically are looking for is here:
https://github.com/enigma-dev/enigma-dev/blob/112dc544d611d5b588e8f0b2e3f193b79e7f0845/ENIGMAsystem/SHELL/Universal_System/roomsystem.cpp#L235

**Comment by RobertBColton** [comment] 2019-03-08 19:37
Alright, sorry it took me so long to try working this issue out, I promise I hadn't forgotten about it. Let me clarify that we have not approved the hack you submitted because I was interested in fixing it the right way for you.

That said, I seem to have fixed the fullscreen toggling for Windows in #1576. Theoretically, I believe it should also fix it for Linux. Let me first say, that the GMS build you have of your game seems to lag a bit when unfullscreening which I guess is just a feature of GMS, but had me thinking it was busted too for a second. Regardless, I would appreciate if you could try out #1576 and let me know how it works for you.

To break down the issue here, I can simply tell you that the problem is the fact that we are still caching the window dimensions, despite Josh's effort in the past to stop doing that. So when the window goes into fullscreen, the generic `enigma::compute_window_size` is calling `window_set_rectangle` which updates the cached window dimensions to cover the entire screen. What we lose is the dimensions of the window prior to being toggled into fullscreen. So my workaround just keeps the cached window dimensions that of the non-fullscreen window while we are in fullscreen mode.

So my plan of attack for fixing this the right way is to discuss what #1576 does with Josh and why it seemingly fixes the problem. I am going to talk to @JoshDreamland about whether he wants to continue caching the window dimensions or not, and what permanent fix to submit.

**Comment by time-killer-games** [comment] 2019-07-27 13:31
My pr fixes this: https://github.com/enigma-dev/enigma-dev/pull/1831 @RobertBColton please close this.

**Closed** 2019-07-27 16:54 UTC
Labels: Platforms, Room Editor, Universal System
