### ISSUE TITLE
Compile Mode Games Only Work in Linux Terminal

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1424] opened 2018-10-27 18:02 UTC
I can only run the game if i open it from the terminal, otherwise...

The Fucking:
![screenshot from 2018-10-27 14-00-40](https://user-images.githubusercontent.com/4379204/47607665-ce38af80-d9f0-11e8-9794-d28fc20a4388.png)

**Comment by RobertBColton** [comment] 2018-10-27 18:54
This is actually a duplicate of #701 and everybody ignored me when I filed that issue.

**Comment by time-killer-games** [comment] 2018-10-30 20:00
I confirm the issue is fixed by that pr.

**Comment by RobertBColton** [comment] 2018-11-17 07:42
This issue upsets me. There's several layers to the issue here too. So what's going on is gcc versions newer than version 6 are building PIEs by default. This causes MIME type detection of the produced executables to see them as shared objects instead of executables. And this is what causes Nautilus to not be able to run the game:
https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1635376

Now, the reason I hate Josh's #1425 proposal is because older gccs complain about not knowing the command line option. We also happen to be using Ubuntu Trusty for Travis still, so obviously it doesn't know about PIE either. The best solution seems to be that we should check the shell to see if gcc is configured with PIE or not.
https://bugs.launchpad.net/sbcl/+bug/1668986
https://launchpadlibrarian.net/309280563/sbcl-1.3.14-gentoo-fix_nopie_for_hardened_toolchain.patch

**Comment by RobertBColton** [comment] 2018-12-17 04:50
Closing as resolved by #1440.

**Closed by RobertBColton** 2018-12-17 04:50 UTC
Labels: Crash, Linux
