### ISSUE TITLE
[SOLVED] Window problems!

### ISSUE THREAD

**Issue by PranavGM** [enigma-dev/enigma-dev#1334] opened 2018-07-25 11:20 UTC
I want my game window so that the player cannot resize it. In the game settings I unchecked 'Allow the player to resize the window' but still there is no effect. Also, the 'Start in fullscreen mode' doesn't work.

I'm making a pixel game which is 384x216. I'm using ENIGMA for Ubuntu 18.04.

**Comment by RobertBColton** [comment] 2018-07-25 11:37
I believe we haven't had this fixed for XLIB - ever actually. That's ok, I can take care of it. It may work right now if you try the ENIGMA Settings->API->Platform : SDL option. Please give that a try.

**Comment by PranavGM** [comment] 2018-07-27 10:32
I tried setting the Platform to SDL, but when I run my game it says 'Game returned 0' (but no errors)

i also put 'window_set_sizeable(false);' in my room's creation code. Still is resizable.

**Comment by RobertBColton** [comment] 2018-07-27 10:43
Ok, sorry about this, I just ran into the fact that SDL-OpenGL is broke on master while working on something totally unrelated. It broke in #1317, and I'll fix it. I'll try to fix the sizeable issue too. Give me a while though I am working on removing some more stuff from the bridges.

**Comment by PranavGM** [comment] 2018-07-27 17:11
Thanks!

**Comment by PranavGM** [comment] 2018-07-28 08:17
I am also experiencing lag in my game. I have just coded the movement and jumping.

**Comment by RobertBColton** [comment] 2018-07-28 13:34
You're welcome, and alright, I've started working on fixes for the two issues. Just for reference, the sizeable option is working in Win32 and SDL, the game setting currently depends on the function, it's just that SDL-OpenGL is broke if you read #1340. I am not sure why actually if you read that issue, but regardless we also have this fixed in the `gl3core` branch. I am also doing #1341 anyway, because we are still keeping our old platforms since they can give better performance in some cases. I'll update you here when and if the pull requests are merged.

In regards to the lag, you'll have to be a lot more specific. Also, it would help if you could narrow down an SSCCE (short self-contained correct example) of the specific feature that is lagging. I may be able to fix it, but I first need to be able to reproduce it.

**Comment by PranavGM** [comment] 2018-07-28 13:56
The lagging is fixed, just had to set the game process priority to normal instead of high.

**Comment by RobertBColton** [comment] 2018-07-28 18:47
I see, yeah, I've not actually cared much for changing the priority over the years and don't think it's a generally good idea anyway. I intend to likely drop it from the game settings UI when I write it in RadialGM.

Regardless, #1341 and #1340 are ready and passing CI now, if you know how to test them I'd appreciate it. I don't have ready access to a Linux machine at the moment. I am going to go see if I can get somebody on Linux to test it out for me and get it reviewed.

**Comment by RobertBColton** [comment] 2018-07-28 19:48
Alright, I got #1340 tested, so you can just `git pull` on master and try the SDL-OpenGL combo again, it should be working now. Please give the `window_set_sizeable` function a test, it's working here on Windows 10.

**Comment by PranavGM** [comment] 2018-09-10 09:47
Thanks, it's now fixed!

**Closed** 2018-09-10 09:49 UTC
Labels: Bridges, Confirmed, Platforms, Reproducible
