### ISSUE TITLE
LateralGM crashes after making compiler.

### ISSUE THREAD

**Issue by pan-te** [enigma-dev/enigma-dev#1013] opened 2016-09-08 12:55 UTC
After installing enigma-dev from git on ArchLinux x86, LateralGM crashes on startup. When I did 'make clean' in CompilerSource, LateralGM started and works until finished building compiler.

[error.txt](https://github.com/enigma-dev/enigma-dev/files/461680/error.txt)

**Comment by RobertBColton** [comment] 2016-09-08 17:51
This one is reproducible as @JoshDreamland is actually not even able to get ENIGMA built on Arch currently.

**Comment by pan-te** [comment] 2016-09-08 22:29
gcc (GCC) 6.1.1 20160802
I'll check it out.

**Comment by JoshDreamland** [comment] 2016-09-09 04:44
Yes, this is a known issue, but I doubt the fix is easy. I haven't found a workaround, as the `<string>` hack I posted on the forums isn't working. My guess is that someone is including a large STL header from the engine, like `<map>` or such. In theory, ENIGMA is capable of parsing these files, but in practice, we're getting a segfault on Arch for some reason or another.

My guess is that running the GCC preprocessor on `SHELLmain.cpp` with that macro hack in place will reveal tons and tons of non-ENIGMA code being included. Figuring out where and removing the directive will solve this for now.

**Comment by fundies** [comment] 2016-09-10 00:26
Heres a backtrace:

> Creating swap.
> Dumping whiteSpace definitions...
> Opening ENIGMA for parse...
> Unimplemented: '::'terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> 
> Program received signal SIGABRT, Aborted.
> 0x00007ffff62dc295 in raise () from /usr/lib/libc.so.6
> (gdb) bt
> #0  0x00007ffff62dc295 in raise () from /usr/lib/libc.so.6
> #1  0x00007ffff62dd6da in abort () from /usr/lib/libc.so.6
> #2  0x00007ffff6bf53dd in __gnu_cxx::__verbose_terminate_handler () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
> #3  0x00007ffff6bf3196 in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
> #4  0x00007ffff6bf31e1 in std::terminate () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
> #5  0x00007ffff6bf33f8 in __cxxabiv1::__cxa_throw (obj=0x7ffff0000940, tinfo=0x7ffff6edc770 <typeinfo for std::bad_alloc>, dest=0x7ffff6bf1540 <std::bad_alloc::~bad_alloc()>)
>     at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:87
> #6  0x00007ffff6bf39ac in operator new (sz=140737488338593) at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/new_op.cc:54
> #7  0x00007ffff6c8999d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffc080, __beg=
>     0x7ffff5be0839 <std::pair<jdi::arg_key const, jdi::definition*>::pair<jdi::arg_key, jdi::definition*, true>(std::pair<jdi::arg_key, jdi::definition*> const&)+35> "H\213E\360H\213P\020H\213E\370H\211P\020\220\311\303UH\211\345AUATSH\203\354(H\211}\330H\211u\320H\211U\310H\213E\310H\211\307\350\377P\366\377I\211\305L\213e\320L\211\346\277\030", __end=<optimized out>)
>     at /build/gcc-multilib/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:219
> #8  0x00007ffff6c899ff in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*> (__end=<optimized out>, __beg=<optimized out>, 
>     this=<optimized out>) at /build/gcc-multilib/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:196
> #9  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (__end=<optimized out>, __beg=<optimized out>, this=<optimized out>)
>     at /build/gcc-multilib/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:215
> #10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=<optimized out>, __str=...)
>     at /build/gcc-multilib/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:400
> #11 0x00007ffff5c274d8 in jdip::context_parser::handle_scope (this=0x64e240, scope=0x7116c0, token=..., inherited_flags=0) at JDI/src/Parser/handlers/handle_scope.cpp:196
> #12 0x00007ffff5c23292 in jdip::context_parser::handle_class (this=0x64e240, scope=0x7fffffffd090, token=..., inherited_flags=0) at JDI/src/Parser/handlers/handle_class.cpp:293
> #13 0x00007ffff5c18387 in jdip::read_type (lex=0x661700, token=..., scope=0x7fffffffd090, cp=0x64e240, herr=0x7ffff5e8e830 <jdi::deh_instance>) at JDI/src/Parser/readers/read_type.cpp:56
> #14 0x00007ffff5c181bf in jdip::read_fulltype (lex=0x661700, token=..., scope=0x7fffffffd090, cp=0x64e240, herr=0x7ffff5e8e830 <jdi::deh_instance>)
>     at JDI/src/Parser/readers/read_type.cpp:36
> #15 0x00007ffff5c1ceee in jdip::context_parser::handle_declarators (this=0x64e240, scope=0x7fffffffd090, token=..., inherited_flags=0, res=@0x7fffffffd088: 0x0)
>     at JDI/src/Parser/handlers/handle_declarators.cpp:49
> #16 0x00007ffff5c20a36 in jdip::context_parser::handle_template (this=0x64e240, scope=0x66efc0, token=..., inherited_flags=0) at JDI/src/Parser/handlers/handle_templates.cpp:110
> #17 0x00007ffff5c27b3d in jdip::context_parser::handle_scope (this=0x64e240, scope=0x66efc0, token=..., inherited_flags=0) at JDI/src/Parser/handlers/handle_scope.cpp:246
> #18 0x00007ffff5c294ce in jdi::context::parse_stream (this=0x64e240, lang_lexer=0x661700, errhandl=0x0) at JDI/src/Parser/base.cpp:88
> #19 0x00007ffff5c28e18 in jdi::context::parse_C_stream (this=0x64e240, cfile=..., fname=0x7ffff5c3b829 "SHELLmain.cpp", errhandl=0x0) at JDI/src/Parser/base.cpp:41
> #20 0x00007ffff5c2a28a in lang_CPP::definitionsModified (this=0x66b8f0, wscode=0x4246b3 "", targetYaml=0x661840 "__GLIBC__") at languages/lang_CPP.cpp:111
> #21 0x00007ffff5b4ff5a in definitionsModified (wscode=0x4246b3 "", targetYaml=0x661840 "__GLIBC__") at main.cpp:137
> #22 0x000000000040c748 in std::_Function_handler<syntax_error* (char const*, char const*), syntax_error* (*)(char const*, char const*)>::_M_invoke(std::_Any_data const&, char const*&&, char const*&&) (__functor=..., __args#0=<unknown type in /home/greg/test3/emake.elf, CU 0x1e56f, DIE 0x28c84>, __args#1=<unknown type in /home/greg/test3/emake.elf, CU 0x1e56f, DIE 0x28c84>)
>     at /usr/include/c++/6.1.1/functional:1726
> #23 0x000000000040abe7 in std::function<syntax_error* (char const*, char const*)>::operator()(char const*, char const*) const (this=0x7fffffffe6f0, __args#0=0x4246b3 "", 
>     __args#1=0x661840 "__GLIBC__") at /usr/include/c++/6.1.1/functional:2136
> #24 0x000000000040a02d in EnigmaPlugin::SetDefinitions (this=0x7fffffffe530, def=0x661840 "__GLIBC__") at EnigmaPlugin.cpp:85
> #25 0x0000000000407b96 in main (argc=3, argv=0x7fffffffea48) at main.cpp:14
> (gdb) quit
>

**Comment by RobertBColton** [comment] 2016-09-19 21:15
Closing as a duplicate of #944

**Closed by RobertBColton** 2016-09-19 21:15 UTC
Labels: Confirmed, Reproducible
