### ISSUE TITLE
Projects randomly get corrupted

### ISSUE THREAD

**Issue by KelvinShadewing** [enigma-dev/enigma-dev#1081] opened 2017-09-30 16:57 UTC
Sometimes when I open a project, it'll say it's corrupted and not load any assets at all. If I open the project file from in Thunar, it treats it like a folder, and lets me view the contents, which all seem to be there, but opening in LateralGM gives me this:

> Operating System: Linux
> Version: 4.8.0-53-generic
> Architecture: amd64
> 
> Java Name: OpenJDK 64-Bit Server VM
> Java Vendor: Oracle Corporation
> Version: 1.8.0_131
> 
> Available processors (cores): 4
> Free memory (bytes): 46409336
> Maximum memory (bytes): 1834483712
> Total memory available to JVM (bytes): 83886080
> 
> File system root: /
> Total space (bytes): 483790184448
> Free space (bytes): 295860555776
> Usable space (bytes): 271261855744
> 
> Stack trace:
> java.lang.NullPointerException
> 	at org.enigma.file.EFileReader.readResource(EFileReader.java:665)
> 	at org.enigma.file.EFileReader.processEntries(EFileReader.java:643)
> 	at org.enigma.file.EFileReader.readNodeChildren(EFileReader.java:621)
> 	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:559)
> 	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:537)
> 	at org.enigma.file.EgmIO.read(EgmIO.java:56)
> 	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
> 	at java.lang.Thread.run(Thread.java:748)

Opening with Game Maker 8 using Wine gives me no issues at all.

**Comment by RobertBColton** [comment] 2017-09-30 19:40
That's using the EGM format which got out of sync with the other project formats (this is my fault). This needs to be fixed but I am too busy running through other issues atm.

From looking at the plugin, it seems LGM is having trouble loading the primary nodes in these EGM files.
https://github.com/enigma-dev/lgmplugin/blob/master/org/enigma/file/EFileReader.java#L643

EGM is just a zip like GMZ is a zip of GMX, thus you can extract it and view it with any ZIP reader like 7-zip. If you look at the ``toc.txt`` file you can see the table of contents for the primary nodes. Regardless, I don't think there's anything wrong with the serialization, hence I am almost certain your game saved fine, it's just the file reader that's broke.

I can't recall the specifics of the problem right now but I can try to get this fixed soon. I am going to close this as a duplicate of https://github.com/enigma-dev/lgmplugin/issues/50 so feel free to post for additional help there on this specific issue. When I have a fix I will post it there, again feel free to post any new tickets if you have any other issues.

**Closed by RobertBColton** 2017-09-30 19:40 UTC
